"""added fuel_entries table

Revision ID: 7afaa6760784
Revises: 522769e0c7bb
Create Date: 2025-12-12 11:41:16.049562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afaa6760784'
down_revision: Union[str, Sequence[str], None] = '522769e0c7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('kilometers', sa.Float(), nullable=False),
    sa.Column('date_of_fuel_entry', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_entry_id'), 'fuel_entry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_entry_id'), table_name='fuel_entry')
    op.drop_table('fuel_entry')
    # ### end Alembic commands ###
